version: '3.7'

services:
  mqtt:
    image: santiago840/mqtt-parking:1.0
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mynetwork

  webapp:
    image: santiago840/app-parking:5.0
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    links: 
      - mqtt
    depends_on:
      - mqtt

networks:
  mynetwork: