version: '3'

services:
  mqtt:
    image: santiago840/mqtt-parking:1.0
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mynetwork

  webapp:
    image: santiago840/app-parking:1.0
    ports:
      - 80:80
    networks:
      - mynetwork
    depends_on:
      - mqtt

networks:
  mynetwork: